# Generated by Django 2.0.5 on 2018-06-05 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('is_available', models.BooleanField()),
                ('is_knockout', models.BooleanField()),
                ('t1_goals', models.IntegerField()),
                ('t2_goals', models.IntegerField()),
                ('t1_pk_goals', models.IntegerField()),
                ('t2_pk_goals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pishbini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_goals', models.IntegerField()),
                ('t2_goals', models.IntegerField()),
                ('t1_pk_goals', models.IntegerField()),
                ('t2_pk_goals', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MrPishbiniBot.Match')),
            ],
        ),
        migrations.CreateModel(
            name='PrePishbini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=10)),
                ('best_player', models.CharField(max_length=15)),
                ('goal_winner', models.CharField(max_length=15)),
                ('most_goals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=4)),
                ('flag', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('user_name', models.CharField(blank=True, max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='prepishbini',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MrPishbiniBot.User'),
        ),
        migrations.AddField(
            model_name='pishbini',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MrPishbiniBot.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ManyToManyField(limit_choices_to=2, to='MrPishbiniBot.Team'),
        ),
    ]
