# Generated by Django 2.0.5 on 2018-06-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MrPishbiniBot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team1',
            new_name='teams',
        ),
        migrations.AlterUniqueTogether(
            name='pishbini',
            unique_together={('match', 'user')},
        ),
    ]
