# Generated by Django 2.0.5 on 2018-06-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MrPishbiniBot', '0003_auto_20180605_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='t1_goals',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='t1_pk_goals',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='t2_goals',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='t2_pk_goals',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pishbini',
            name='t1_pk_goals',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pishbini',
            name='t2_pk_goals',
            field=models.IntegerField(blank=True),
        ),
    ]
